language: node_js
cache: yarn
node_js:
   - "6.9.4"
   - "7.4.0"
matrix:
  allow_failures:
    - node_js: "7.4.0"
  fast_finish: true
notifications:
  email: false
  webhooks: https://ambrosio-tele.herokuapp.com/sacarinobot/travisci/133188453
  on_success: always # default: always
  on_failure: always # default: always
  on_start: always   # default: never
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
